#ifndef __REMOTE_DESKTOP_COMMON_H
#define __REMOTE_DESKTOP_COMMON_H

#define REMOTE_DESKTOP_VERSION       1

#define RD_INPUT_TYPE_MOUSE_INPUT     0
#define RD_INPUT_TYPE_KEYBOARD_INPUT  1


#define RD_KEYEVENTF_EXTENDEDKEY 0x0001
#define RD_KEYEVENTF_KEYUP       0x0002
#define RD_KEYEVENTF_SCANCODE    0x0008
#define RD_KEYEVENTF_UNICODE     0x0004

#define RD_MOUSEEVENTF_MOVE              0x0001	
#define RD_MOUSEEVENTF_LEFTDOWN          0x0002
#define RD_MOUSEEVENTF_LEFTUP            0x0004
#define RD_MOUSEEVENTF_RIGHTDOWN         0x0008
#define RD_MOUSEEVENTF_RIGHTUP           0x0010
#define RD_MOUSEEVENTF_MIDDLEDOWN        0x0020
#define RD_MOUSEEVENTF_MIDDLEUP          0x0040
#define RD_MOUSEEVENTF_XDOWN             0x0080
#define RD_MOUSEEVENTF_XUP               0x0100
#define RD_MOUSEEVENTF_WHEEL             0x0800
#define RD_MOUSEEVENTF_HWHEEL            0x1000
#define RD_MOUSEEVENTF_MOVE_NOCOALESCE   0x2000
#define RD_MOUSEEVENTF_VIRTUALDESK       0x4000
#define RD_MOUSEEVENTF_ABSOLUTE          0x8000
#define RD_MOUSEEVENTF_LEFT_DBCLICK      0x10000

#endif
